export const languages = [
  {
    lang: "English",
    loginText: "Sign in by mail",
    signUpText: "Sign Up",
    nameSuccess: "Looks Good!",
    emailSuccess: "Email looks good!",
    passwordSuccess: "Password looks good!",
    continueText: "Continue",
    emailLabel: "Email Address",
    passwordLabel: "Password",
    notPublishedText: "Not published",
    createSimilar: "Create a similar post",
  },
  {
    lang: "Русский",
    loginText: "Войти по почте",
    signUpText: "Зарегистрироваться",
    nameSuccess: "Отлично!",
    emailSuccess: "Email выглядит правильно!",
    passwordSuccess: "Пароль выглядит хорошо!",
    continueText: "Продолжить",
    emailLabel: "Адрес электронной почты",
    passwordLabel: "Пароль",
    notPublishedText: "Не опубликован",
    createSimilar: "Создать похожий пост",
  },
  {
    lang: "Қазақша",
    loginText: "Пошта арқылы кіру",
    signUpText: "Тіркелу",
    nameSuccess: "Дұрыс енгізілді!",
    emailSuccess: "Электрондық пошта дұрыс енгізілген!",
    passwordSuccess: "Құпия сөз дұрыс енгізілді",
    continueText: "Жалғастыру",
    emailLabel: "Электрондық пошта мекенжайы",
    passwordLabel: "Құпиясөз",
    notPublishedText: "Жарияланбаған",
    createSimilar: "Ұқсас пост жасау",
  },
];

export const socials = [
    {socialMedia: "Facebook"},
    {socialMedia: "LinkedIn"},
    {socialMedia: "Instagram"},
]